image: alpine:latest
before_script: |
  apk update
  apk add python3 py3-pip
  PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install -r requirements.txt
pages:
  stage: deploy
  script: |
    sh ./scripts/make.sh
  artifacts:
    paths:
      - site
  publish: site
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
