name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  page_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt update
        sudo apt install python3 python3-pip
        PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install -r requirements.txt
        sh ./scripts/make.sh
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site
